<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="18" passed="14">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="1123" started-at="2015-07-15T19:01:15Z" finished-at="2015-07-15T19:01:16Z">
    <groups>
      <group name="ID">
        <method signature="TestNameIDGroup.EmployeeTest_C()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_C" class="myApplicationTest.TestNameIDGroup"/>
        <method signature="TestNameIDGroup.EmployeeTest_D()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_D" class="myApplicationTest.TestNameIDGroup"/>
      </group> <!-- ID -->
      <group name="Name">
        <method signature="TestNameIDGroup.EmployeeTest_A()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_A" class="myApplicationTest.TestNameIDGroup"/>
        <method signature="TestNameIDGroup.EmployeeTest_B()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_B" class="myApplicationTest.TestNameIDGroup"/>
        <method signature="TestNameIDGroup.EmployeeTest_C()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_C" class="myApplicationTest.TestNameIDGroup"/>
        <method signature="TestNameIDGroup.EmployeeTest_D()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_D" class="myApplicationTest.TestNameIDGroup"/>
      </group> <!-- Name -->
    </groups>
    <test name="Command line test" duration-ms="1123" started-at="2015-07-15T19:01:15Z" finished-at="2015-07-15T19:01:16Z">
      <class name="myApplicationTest.TestNameIDGroup">
        <test-method status="PASS" signature="EmployeeTest_B()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_B" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest_B -->
        <test-method status="PASS" signature="EmployeeTest_A()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_A" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest_A -->
        <test-method status="FAIL" signature="EmployeeTest_D()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_D" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1001] but found [100001]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1001] but found [100001]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:492)
	at org.testng.Assert.assertSame(Assert.java:443)
	at org.testng.Assert.assertSame(Assert.java:453)
	at myApplicationTest.TestNameIDGroup.EmployeeTest_D(TestNameIDGroup.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest_D -->
        <test-method status="PASS" signature="EmployeeTest_C()[pri:0, instance:myApplicationTest.TestNameIDGroup@13afe78]" name="EmployeeTest_C" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest_C -->
      </class> <!-- myApplicationTest.TestNameIDGroup -->
      <class name="myApplicationTest.TestNameTest1">
        <test-method status="PASS" signature="testStarted()[pri:0, instance:myApplicationTest.TestNameTest1@163425a]" name="testStarted" is-config="true" duration-ms="10" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStarted -->
        <test-method status="PASS" signature="testStarted()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="testStarted" is-config="true" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStarted -->
        <test-method status="FAIL" signature="EmployeeTest()[pri:0, instance:myApplicationTest.TestNameTest1@163425a]" name="EmployeeTest" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [WillSmitt] but found [Will Smitt]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [WillSmitt] but found [Will Smitt]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at myApplicationTest.TestNameTest1.EmployeeTest(TestNameTest1.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest -->
        <test-method status="PASS" signature="testFinished()[pri:0, instance:myApplicationTest.TestNameTest1@163425a]" name="testFinished" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFinished -->
        <test-method status="PASS" signature="testStarted()[pri:0, instance:myApplicationTest.TestNameTest1@163425a]" name="testStarted" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStarted -->
        <test-method status="PASS" signature="testFinished()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="testFinished" is-config="true" duration-ms="0" started-at="2015-07-15T22:01:16Z" finished-at="2015-07-15T22:01:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFinished -->
        <test-method status="PASS" signature="testFinished()[pri:0, instance:myApplicationTest.TestNameTest1@163425a]" name="testFinished" is-config="true" duration-ms="0" started-at="2015-07-15T22:01:16Z" finished-at="2015-07-15T22:01:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFinished -->
      </class> <!-- myApplicationTest.TestNameTest1 -->
      <class name="myApplicationTest.TestSuiteAllTests">
        <test-method status="PASS" signature="EmployeeTest()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest" is-config="true" duration-ms="30" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest -->
        <test-method status="FAIL" signature="EmployeeTest9()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest9" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1000000.0] but found [974.709]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1000000.0] but found [974.709]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:209)
	at org.testng.Assert.assertEquals(Assert.java:222)
	at myApplicationTest.TestSuiteAllTests.EmployeeTest9(TestSuiteAllTests.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest9 -->
        <test-method status="PASS" signature="EmployeeTest6()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest6" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest6 -->
        <test-method status="PASS" signature="EmployeeTest7()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest7" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest7 -->
        <test-method status="PASS" signature="EmployeeTest2()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest2" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest2 -->
        <test-method status="PASS" signature="EmployeeTest10()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest10" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest10 -->
        <test-method status="PASS" signature="EmployeeTest3()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest3" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest3 -->
        <test-method status="FAIL" signature="EmployeeTest5()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest5" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1001] but found [100001]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1001] but found [100001]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:492)
	at org.testng.Assert.assertSame(Assert.java:443)
	at org.testng.Assert.assertSame(Assert.java:453)
	at myApplicationTest.TestSuiteAllTests.EmployeeTest5(TestSuiteAllTests.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest5 -->
        <test-method status="PASS" signature="EmployeeTest4()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest4" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest4 -->
        <test-method status="PASS" signature="EmployeeTest8()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest8" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest8 -->
        <test-method status="PASS" signature="EmployeeTest()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="EmployeeTest" duration-ms="0" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmployeeTest -->
        <test-method status="PASS" signature="waitLongTime()[pri:0, instance:myApplicationTest.TestSuiteAllTests@d072a9]" name="waitLongTime" duration-ms="1061" started-at="2015-07-15T22:01:15Z" finished-at="2015-07-15T22:01:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- waitLongTime -->
      </class> <!-- myApplicationTest.TestSuiteAllTests -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
